default: &defaults
  book_path: "/books"
  upload_url: "/uploads"
  admin_emails: ['pmq2001@gmail.com']
  email_sender: '"T2Ku" <t2ku@t2ku.org>'

development:
  <<: *defaults
  domain: "lvh.me"

test:
  <<: *defaults

production:
  <<: *defaults
